name: 同步文件

on: [push]

env:
  Myki: ku
jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
#    - name: Set up Python 3.10
#      uses: actions/setup-python@v2
#      with:
#        python-version: 3.9
#        architecture: 'x64'
#    - run: pip install -r requirements.txt
#    - run: python3 download_jd_files.py

    - name: python
      run: |
        python3 download_jd_files.py

    - name: list files
      run: |
        tree .

    - name: Commit files
      #if: steps.IFFI.outputs.YN == 'dirty'
      continue-on-error: true
      run: |
        git config --local user.email "21kixc@gmail.com"
        git config --local user.name "21ki"
        git add .
        git commit -m "sync-bot"

    - name: Add env to system path
      id: IFFI
      #run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
       # echo "UPSTREAM_URL=${{ env.Myki }}" >> $GITHUB_ENV
      run: echo "::set-output name=YN::$(git diff --quiet || echo 'dirty')"

    - name: Push changes
      #if: steps.IFFI.outputs.YN == 'dirty'
      continue-on-error: true
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

