name: 同步文件

on: [push]

env:
  Myki: ku
jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
#    - name: Set up Python 3.10
#      uses: actions/setup-python@v2
#      with:
#        python-version: 3.9
#        architecture: 'x64'
#    - run: pip install -r requirements.txt
#    - run: python3 download_jd_files.py

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo "UPSTREAM_URL=${{ env.Myki }}" >> $GITHUB_ENV
        
    - name: python
      run: |
        python3 download_jd_files.py

    - name: Merge upstream
      run: |
        git config --global user.name '21ki'
        git config --global user.email '21kixc@gmail.com'
        git add .
        git commit 'python_download'
        git push origin main
